---
kind: pipeline
type: docker
name: default

steps:
  - name: setup
    image: node:20-alpine
    when:
      event:
        - push
    commands:
      - yarn install --frozen-lockfile

  - name: prettier
    image: node:20-alpine
    when:
      event:
        - push
    depends_on:
      - setup
    commands:
      - yarn run prettier:check

  - name: eslint
    image: node:20-alpine
    when:
      event:
        - push
    depends_on:
      - setup
    commands:
      - yarn lint

  - name: build
    image: node:20-alpine
    when:
      event:
        - push
    depends_on:
      - setup
    commands:
      - yarn build
