import Lyrics from "@/components/lyrics";
import BackButton from "@/components/back-button";
import Footer from "@/components/footer";
import BeerContainer from "@/components/beer/beer-container";

const foreverAlone = [
  [
    <b>Faddere</b>,
    "No one can say I didn't try",
    <b>Alle</b>,
    "Tried everything to make you feel what I feel",
    <b>Går Datateknologi</b>,
    "Well, I guess I pushed to hard",
    <b>Går Cyber</b>,
    "And now you're slipping away",
    <b>Har hatt kjæreste</b>,
    "Feels like my love for you",
    <b>Jukset på en prøve</b>,
    "Is stopping you from being you",
    <b>De som har hatt friår</b>,
    "You shine best without me",
    <b>Fadderbarn</b>,
    "Like all the ones I had before",
    <b>ALLE!</b>,
    "I am forever alone",
    <b>Har vært i milla</b>,
    "Home alone eating sushi for two",
    <b>Har grått i 2024</b>,
    "Home alone and I'm waiting for someone who never shows up",
    <b>Er hyped for i dag</b>,
    "Ooh, and I'm lonely, I'm angry I'm tired",
    <b>Spydd på fest</b>,
    "You're only giving med drips of your love",
    <b>Har blitt blokket på snap av noen før</b>,
    "Appointments, you've been breaking them all",
    <b>Har blokket noen før</b>,
    "It's like a never ending story",
    <b>Har hatt blackout</b>,
    "I give, and you take, and I give, and you take",
    <b>Har på seg undertøy</b>,
    "Feels like my love for you",
    <b>Alle</b>,
    "Is stopping you from being you",
    <b>Gått på folkehøyskole</b>,
    "You shine best without me",
    <b>Alle</b>,
    "Like all the ones I had before",
    <b>Er singel</b>,
    "I am forever alone",
    <b>Fått 2 på en prøve</b>,
    "When I held your hand you were sincere",
    <b>Ditchet skolen</b>,
    "But did you ever think about me when I wasn't near you",
    <b>Drikker noe annet enn øl</b>,
    "Why would you ever put me first?",
    <b>Har vært på tinderdate</b>,
    "You are second to none",
    <b>Har onanert</b>,
    "I wanted to leave, I tried to find someone new",
    <b>Studerer</b>,
    "But I always end up still wanting you",
    <b>Tror de blir fulle i kveld</b>,
    "Why do I do this to myself?",
    <b>Hoppet i fallskjerm</b>,
    "Feels like my love for you",
    <b>Har farget håret før</b>,
    "Is stopping you from being you",
    <b>Blitt tatt med fake leg</b>,
    "You shine best without me",
    <b>Har et crush</b>,
    "Like all the ones I had before",
    <b>Blir fort forelsket</b>,
    "I am forever alone",
    <b>Alle</b>,
    "When I'm with you, you tell me you love me",
    <b>Skulle tatt en tur til specsavers</b>,
    "When you're not I don't even exist",
    <b>Hadde solgt bilde av føttene for 100 kr</b>,
    "If I ask you if you want to hang with me",
    <b>Har dusjet med en annen</b>,
    "You got a thousand excuses rehearsed",
    <b>Alle med blondt hår</b>,
    "But when you're drunk and got no place to hide",
    <b>Alle som er single</b>,
    "Who's the one you always call?",
    <b>Alle som skal bli fulle i dag</b>,
    "Feels like my love for you",
    <b>Hadde gått på date med en sugerdaddy for 10 000 kr</b>,
    "Is stopping you from being you",
    <b>Fadderbarn</b>,
    "You shine best without me",
    <b>Alle</b>,
    "Like all the ones I had before",
    <b>Kommet hjem i 06 tiden</b>,
    "I am forever alone",
    <b>Har flyttet ut</b>,
    "My love for you",
    <b>Drikker sprit i dag</b>,
    "Is stopping you from being you",
    <b>Har vært på utested</b>,
    "You shine best without me",
    <b>Fadderbarn</b>,
    "Like all the ones I had before",
    <b>ALLE</b>,
    "I am forever alone",
  ],
];

const ForeverAlonePage = () => {
  return (
    <main className="overflow-x-hidden">
      <BackButton className="absolute top-4 left-4 z-10" href="/" />
      <BeerContainer color="green" className="min-h-dvh">
        <Lyrics title="Forever Alone" lyrics={foreverAlone} />
        <Footer />
      </BeerContainer>
    </main>
  );
};

export default ForeverAlonePage;
